RTC<-ldply(RTC4[1:6],data.frame)


light<-c("DIQMTQSPSSLSASVGDRVTITCKTSQDINKYMAWYQQTPGKAPRLLIHYTSALQPGIPSRFSGSGSGRDYTFTISSLQPEDIATYYCLQYDNLWTFGQGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC")
heavy<-c("QVQLVQSGAEVKKPGASVKVSCKASGFNIKDTYIHWVRQAPGQRLEWMGRIDPANGYTKYDPKFQGRVTITADTSASTAYMELSSLRSEDTAVYYCAREGYYGNYGVYAMDYWGQGTLVTVSSASTKGPSVFPLAPCSRSTSESTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTKTYTCNVDHKPSNTKVDKRVESKYGPPCPSCPAPEFLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSQEDPEVQFNWYVDGVEVHNAKTKPREEQFNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKGLPSSIEKTISKAKGQPREPQVYTLPPSQEEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSRLTVDKSRWQEGNVFSCSVMHEALHNHYTQKSLSLSLGK")

length(strsplit(heavy,"")[[1]])
light2<-stringr::str_extract_all(light,"..K..")
heavy2<-stringr::str_extract_all(heavy,"..K..")

heavy1<-as.data.frame(heavy1)
heavy2<-as.data.frame(heavy2)
light1<-as.data.frame(light1)
light2<-as.data.frame(light2)
colnames(heavy1)<-c("seq")
colnames(heavy2)<-c("seq")
colnames(light1)<-c("seq")
colnames(light2)<-c("seq")
dat<-unique(rbind(heavy1,heavy2,light1,light2))

specifcity<-RTC$Peptide.1
SPEC6<-str_extract(specifcity,"..K..")

SPEC<-ldply(list(SPEC11,SPEC22,SPEC33,SPEC44,SPEC55,SPEC66),data.frame)
SPEC<-na.omit(SPEC)

SPEC66<-str_replace(SPEC6,"\\[","X")
SPEC11<-str_replace(SPEC11,"\\]","X")


#randomly sample 10000 rows as the icelogo generator cant handle more
SPEC2<-as.data.frame(SPEC[sample(nrow(SPEC),10000),])

write.csv2(dat,"spec_fasta.csv")
getwd()

